name: jobs examples

on:
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step of job1
        run: echo Hello world ! job1.
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step of job2
        run: echo Hello world! Job2.
