name: jobs examples

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: create an artifact for reuse
        run: echo "Full featured artifact" > build-result.txt
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: use of artifact created
        run: ls build-result.txt
