name: jobs examples

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: example of a bad command
        run: ecko Hello world ! Build.
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy step
        run: echo Hello world! Deploy.
